# Generated by Django 5.2.6 on 2025-09-03 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название источника')),
                ('type', models.CharField(choices=[('film', 'Фильм'), ('book', 'Книга'), ('other', 'Другое')], default='other', max_length=16, verbose_name='Тип')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
                'unique_together': {('title', 'type')},
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст цитаты')),
                ('normalized_text', models.CharField(editable=False, max_length=2048, unique=True)),
                ('base_weight', models.FloatField(default=1.0, verbose_name='Базовый вес')),
                ('likes', models.PositiveIntegerField(default=0)),
                ('dislikes', models.PositiveIntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='quotes.source', verbose_name='Источник')),
            ],
            options={
                'ordering': ['-likes', '-views', '-created_at'],
            },
        ),
    ]
